Fix OpenSuse42.1 ci test

diff --git a/scripts/test/ci_tests/OpenSuse42.1/Dockerfile b/scripts/test/ci_tests/OpenSuse42.1/Dockerfile
--- a/scripts/test/ci_tests/OpenSuse42.1/Dockerfile
+++ b/scripts/test/ci_tests/OpenSuse42.1/Dockerfile
@@ -1,6 +1,6 @@
 FROM opensuse/archive:42.1
 
-RUN zypper --non-interactive install docker
+RUN zypper --non-interactive install docker || true # zypper fails with error code 106, because some repositories aren't reachable
 
 COPY run_ci_test_within_docker_bash_below_4.4.sh /run_ci_test_within_docker_bash_below_4.4.sh
 ENTRYPOINT ["/run_ci_test_within_docker_bash_below_4.4.sh"]
